version: "2.2"

services:

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        volumes:
            - elastic-data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
        networks:
            - webnet

    kibana:
        image: docker.elastic.co/kibana/kibana:7.11.1
        environment:
            ELASTICSEARCH_URL: http://elastic:9200
            ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
        networks:
            - webnet
        ports:
            - 5601:5601

networks:
    webnet:

volumes:
  elastic-data:
